feat: add team section and image assets
DevRel-Community-Africa/devrelcomafrica.xyz pull request #10
Opened 2023-08-01 19:05 UTC by Timimah

2023-08-01 19:52 UTC, hacktivist123 commented
This PR is failing

2023-08-03 11:13 UTC, 0xJamin requested changes
Hi @Timimah  I requested a few changes for you to update on your branch.

Also when creating your PR , you should only merge to the `develop` branch and not the`main` branch.

Can you update that on the PR?

2023-08-03 11:13 UTC, codejagaban commented on components/organisms/TeamSection/TeamSection.tsx
> +        <div className="bg-[#99999980] h-[21em] md:w-[22em]">
You can use a bg-gray-300  for this background

2023-08-03 11:13 UTC, codejagaban commented on components/organisms/TeamSection/TeamSection.tsx
> +          <img className="object-cover h-[21em]" src={imgSource} alt="" />
Can we use the Nextjs image component here for image optimization?

2023-08-03 11:13 UTC, 0xJamin commented on components/organisms/TeamSection/TeamSection.tsx
> +                <path
Can we save icons in the public folder and import them here using the Nextjs Image component for a cleaner look? 😉

2023-08-03 11:13 UTC, 0xJamin commented on components/organisms/TeamSection/TeamSection.tsx
> +  function Card({ imgSource, title, position }) {
instead of having the card component inside the `TeamSection`, add it to the atoms folder and import it here

2023-08-03 11:13 UTC, 0xJamin commented on components/organisms/TeamSection/TeamSection.tsx
> +export default function TeamSection() {
`export function TeamSection() {}`

2023-08-03 11:13 UTC, 0xJamin commented on components/organisms/TeamSection/index.ts
> +import TeamSection from "./TeamSection";
```
import { TeamSection } from "./TeamSection";

export default TeamSection;

```

2023-08-03 11:49 UTC, Timimah commented on components/organisms/TeamSection/TeamSection.tsx
> +        <div className="bg-[#99999980] h-[21em] md:w-[22em]">
Noted

2023-08-03 12:10 UTC, Timimah commented on components/organisms/TeamSection/TeamSection.tsx
> +          <img className="object-cover h-[21em]" src={imgSource} alt="" />
Change made

2023-08-03 17:30 UTC, closed without merging