About the team
DevRel-Community-Africa/devrelcomafrica.xyz pull request #12
Opened 2023-08-03 17:33 UTC by Timimah

2023-08-04 18:05 UTC, 0xJamin requested changes
Hi @Timimah some small changes for you to adjust to, good work so far👌🏼

2023-08-04 18:05 UTC, 0xJamin commented on components/atoms/Card/Card.tsx
> +export function Card({ imgSource, title, position }: CardTypes) {
for easy understanding this can be `{image, name, role}`

2023-08-04 18:05 UTC, 0xJamin commented on components/atoms/Card/Card.tsx
> +        <div className="bg-gray-300 h-[21em] md:w-[22em]">
Do we still need this height after specifying the width of the image?

2023-08-04 18:05 UTC, 0xJamin commented on components/atoms/Card/types.ts
for easy understanding this can be `{image, name, role}`

2023-08-04 18:05 UTC, 0xJamin commented on components/organisms/TeamSection/TeamSection.tsx
> +    <section id="teams" className="bg-[#E4F4E9] p-8 flex flex-col gap-8">
We already have the background color in the project as a tailwind config, you can access using `bg-primary-light`

2023-08-04 18:10 UTC, 0xJamin requested changes
@Timimah please run your branch locally to ensure everything works fine and let me know

2023-08-04 18:10 UTC, 0xJamin commented on pages/index.tsx
> +develop
@Timimah this is what is causing this PR deployment to fail on netlify can you remove this?

2023-08-04 18:10 UTC, 0xJamin commented on pages/index.tsx
> +develop
This should be removed as well

2023-08-07 12:38 UTC, Timimah commented on components/atoms/Card/Card.tsx
> +        <div className="bg-gray-300 h-[21em] md:w-[22em]">
Nope. Thanks for pointing that out. fixed

2023-08-09 19:16 UTC, 0xJamin requested changes
@Timimah  Here's a screenshot of how this section looks like on mobile and desktop, can please fix it🙏🏽
I also dropped some comments  that needs to be looked into.

<img width="2554" alt="Screenshot 2023-08-09 at 8 11 50 PM" src="https://github.com/DevRel-Community-Africa/devrelcomafrica.xyz/assets/34829458/2c43f76b-b960-4b45-83dd-aa1636caca44">
<img width="949" alt="Screenshot 2023-08-09 at 8 12 42 PM" src="https://github.com/DevRel-Community-Africa/devrelcomafrica.xyz/assets/34829458/ef84ee0f-fa23-4c6b-8eb7-7dd3b2d769bd">

2023-08-09 19:16 UTC, 0xJamin commented on components/atoms/Card/Card.tsx
> +      <div className="bg-gray-300 md:w-[22em]">
Images are not responsive

2023-08-09 19:16 UTC, 0xJamin commented on components/organisms/TeamSection/TeamSection.tsx
> +      <div className="font-semibold text-xl text-left">Meet the Team</div>
font size doesn't match the one on the design

2023-08-09 19:16 UTC, 0xJamin commented on components/organisms/TeamSection/TeamSection.tsx
> +      <div className="font-semibold text-xl text-left">Meet the Team</div>
there's no container to make this section responsive

2023-09-27 10:28 UTC, seunbayo commented
@0xJamin  are the changes completed?

2023-09-27 10:45 UTC, 0xJamin commented
> @0xJamin are the changes completed?

@seunbayo No

2023-10-19 09:05 UTC, closed without merging