feat: develop mission section with responsiveness
DevRel-Community-Africa/devrelcomafrica.xyz pull request #13
Opened 2023-09-22 14:22 UTC by DesmondSanctity

- [x] Mission Section
- [x] Responsiveness
- [ ] Add Vector

2023-09-29 23:13 UTC, hacktivist123 commented
Hello @DesmondSanctity is this ready for merge? 

What is left?

2023-09-29 23:15 UTC, DesmondSanctity commented
> Hello @DesmondSanctity is this ready for merge? 
> 
> What is left?

Not yet ready. There's a vector image I need to add in that mission section background. I will work on it this weekend.

2023-09-29 23:16 UTC, hacktivist123 commented
> > Hello @DesmondSanctity is this ready for merge?
> > What is left?
> 
> Not yet ready. There's a vector image I need to add in that mission section background. I will work on it this weekend.

You sure? I could just work on it myself tonight

2023-09-29 23:17 UTC, DesmondSanctity commented
> > > Hello @DesmondSanctity is this ready for merge?
> > > What is left?
> > 
> > Not yet ready. There's a vector image I need to add in that mission section background. I will work on it this weekend.
> 
> You sure? I could just work on it myself tonight 

Yeah definitely. I will do it

2023-10-08 11:57 UTC, 0xJamin commented
Hi @DesmondSanctity What's the update on this issue?

2023-10-08 15:11 UTC, 0xJamin requested changes

2023-10-08 15:11 UTC, codejagaban commented on components/organisms/MissionSection/MissionSection.tsx
> +      titleS:
What's this `titleS` exactly?

2023-10-08 15:11 UTC, codejagaban commented on components/organisms/MissionSection/MissionSection.tsx
> +        <div className="mt-6 sm:mt-6 md:mt-8 lg:mt-10 text-neutral-600 text-sm font-[300] sm:text-lg md:text-xl lg:text-2xl font-normal">
Why do you have `font-[300]` and `font-normal` in the same place?

2023-10-08 15:11 UTC, codejagaban commented on components/organisms/MissionSection/MissionSection.tsx
> +                className="bg-[#FFF] p-2 h-[120px] sm:h-[300px] md:h-[250px] lg:h-[300px] xl:h-[280px]"
why can't you use `bg-white` here? Or is white a custom colour?🤔
Also are reason why you're specifying the height of of this div for every screen size?🤔

IMO I don't think it's necessary, also the height doesn't match what is on the designs on Figma

2023-10-08 15:11 UTC, codejagaban commented on components/organisms/MissionSection/MissionSection.tsx
> +                  {mission.titleS}
Why exactly do we have two `mission.title`?

2023-10-08 15:11 UTC, codejagaban commented on components/organisms/MissionSection/MissionSection.tsx
> +        {/* <div className="mt-12 flex flex-col sm:flex-row gap-10">
Remove comments

2023-10-08 15:11 UTC, codejagaban commented on tailwind.config.js
> +      screens: {
This comes by default with tailwindCSS why do we need to specify them here?

2023-10-19 09:04 UTC, merged